config/routes.rb
Rails.application.routes.draw do
  resources :authors

  resources :facts

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :facts
end

app/models/fact.rb
class Fact < ActiveRecord::Base
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  def index
    @facts = Fact.all
  end

  def show
    @fact = Fact.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/authors/index.html.erb
<h1>Authors and their Facts</h1>

<% @authors.each do |author| %>
  <h2>Author: <%= link_to(author.name, author) %></h2>
  <% author.facts.each do |fact| %>
    <h3>Fact: <%= link_to(fact.body, fact_path(fact)) %></h3>
  <% end %>
  <br />
<% end %>

app/views/authors/show.html.erb
<h1>One Author and their Facts</h1>

<h2>Author: <%= @author.name %></h2>
<% @author.facts.each do |fact| %>
  <h3>Fact: <%= link_to(fact.body, fact_path(fact)) %></h3>
<% end %>

<h4><%= link_to "Back to Author's index", authors_path %></h4>

app/views/facts/index.html.erb
<h1>Facts and their Authors</h1>

<% @facts.each do |fact| %>
  <h2>Fact: <%= link_to(fact.body, fact) %></h2>
  <h3>Author: <%= link_to(fact.author.name, author_path(fact.author)) %></h3>
  <br/>
<% end %>

app/views/facts/show.html.erb
<h1>One Fact and their Author</h1>

<h2>Fact: <%= @fact.body %></h2>
<h3>Author: <%= link_to(@fact.author.name, author_path(@fact.author)) %></h3>

<h4><%= link_to "Back to Fact's index", facts_path %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DogFacts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>